### ISSUE TITLE
Loading replayCache.json does nothing

### ISSUE THREAD

**Issue by ncondron42** [vinceau/project-clippi#116]
Hi I generated a combo json using default settings. Then I switch to the Playback Queue and I select load JSON and select the file. Nothing happens (that I can tell). I can select 1 or more slp files to add the queue no problem. It is just the JSON file that seems to be the issue. It might be because the file is very large... (I analyzed ~5000 slp games to create the JSON). I have attached the replayCache here:

[replayCache.zip](https://github.com/vinceau/project-clippi/files/5781061/replayCache.zip)

**Comment by vinceau** [comment]
The JSON file that you have provided has not been created with Clippi. I don't know where you got it from but it's definitely not a valid JSON file which is why nothing happens when you load it.

**Comment by ncondron42** [comment]
The JSON file most certainly was created with Clippi. I would have no reason to lie to you. I don't want to insult your intelligence, but did you unzip the file? Even if it is formatted incorrectly, you should be able to tell that the file was generated by Clippi. I checked the formatting with an online tool:

![screenshot-json](https://user-images.githubusercontent.com/10557166/103923224-d7e6f300-50e2-11eb-8fa7-3fc19e5298c8.png)

**Comment by vinceau** [comment]
Look mate. With all due respect, I've spent more than a year working on this project so I'm quite aware of the type of JSON files that it outputs. The fact that you had to use an online formatting tool to check the contents of the JSON shows that it's not generated by Clippi since Clippi will auto-format the JSON nicely by default.

The valid JSON format that Clippi expects is like this:
```json
{
  "mode": "queue",
  "replay": "",
  "isRealTimeMode": false,
  "outputOverlayFiles": true,
  "queue": [
    {
      "path": "C:\\Users\\Vince\\Documents\\Slippi\\2021-01\\Game_20210106T205856.slp",
      "gameStartAt": "01/06/21 8:58 pm",
      "startFrame": 10182,
      "endFrame": 11085
    }
  ]
}
```

Like I said before, I don't know where you got your JSON file, but my recommendations to you are to:

1) Reinstall Clippi
2) Regenerate your JSON file
